name: MongoDB Snapshot Backup

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Choose environment'
          required: true
          default: 'production'

jobs:
    backup:
        runs-on: ubuntu-latest
        container: mongo:6.0
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Create MongoDB Backup
              id: mongo_backup
              env:
                MONGO_URI: ${{ secrets.MONGO_URI }}
              run: |
                TIMESTAMP=$(date +%Y_%m_%d_%H_%M)
                BACKUP_FILE="backup_$TIMESTAMP.gz"
                mongodump --uri="$MONGO_URI" --archive="$BACKUP_FILE" --gzip
                echo "Backup created: $BACKUP_FILE"
                echo "BACKUP_FILE=$BACKUP_FILE" >> $GITHUB_OUTPUT

            - name: Upload to Google Drive
              uses: willo32/google-drive-upload-action@v1
              with:
                parent_folder_id: ${{ secrets.GDRIVE_FOLDER_ID }}
                target: ${{ steps.mongo_backup.outputs.BACKUP_FILE }} 
                credentials: ${{ secrets.GDRIVE_TOKEN }}