name: MongoDB Snapshot Backup

on:
  workflow_dispatch:

jobs:
  generate-filename:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.generate_filename.outputs.filename }}

    steps:
      - name: Generate Filename
        id: generate_filename
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          FILENAME="mongodb_backup_$TIMESTAMP.gz"
          echo "Generated filename: $FILENAME"
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

  backup:
    needs: generate-filename
    runs-on: ubuntu-latest
    container: mongo:latest

    steps:
      - name: Backup MongoDB
        run: |
          mongodump \
            --uri="${{ secrets.MONGO_URI }}" \
            --archive=${{ needs.generate-filename.outputs.filename }} \
            --gzip
          echo "Backup completed: ${{ needs.generate-filename.outputs.filename }}"

      - name: Upload Backup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mongodb-backup
          path: ${{ needs.generate-filename.outputs.filename }}

  upload:
    needs: [backup, generate-filename]   
    runs-on: ubuntu-latest
    container: python:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Backup Artifact
        uses: actions/download-artifact@v4
        with:
          name: mongodb-backup
          path: backup-files   

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Upload to Dropbox
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python upload_backup.py backup-files/${{ needs.generate-filename.outputs.filename }}